databases:
  - name: to_exercise_projectdb
    plan: free
    databaseName: to_exercise_project
    user: to_exercise_project
    password: abc123.
services:
  - type: web
    plan: free
    name: to_exercise_project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT to_exercise_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: to_exercise_projectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"  # ¡Importante para producción!
      - key: ALLOWED_HOSTS
        value: "https://to-exercise-project-pt3a.onrender.com"  # Reemplaza con tu URL real
      - key: WEB_CONCURRENCY
        value: 4