databases:
  - name: to_exercise_projectdb
    plan: free
    databaseName: to_exercise_project
    user: to_exercise_project

services:
  - type: web
    plan: free
    name: to_exercise_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python to_exercise_project/manage.py runserver"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: to_exercise_projectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
