# docker-compose.yml (solo para desarrollo local)
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:10000 to_exercise_project.wsgi:application
    environment:
      - DATABASE_URL=postgres://nico:abc123.@basededatos:5432/example
    depends_on:
      - basededatos
  basededatos:
    image: postgres:15
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: nico
      POSTGRES_PASSWORD: abc123.
    volumes:
      - postgres_data:/var/lib/postgresql/data