services:
  web:
    build: .
    command: ./wait-for-it.sh basededatos:5432 -- gunicorn --bind 0.0.0.0:10000 --log-level debug to_exercise_project.wsgi:application

    volumes:
      - .:/code
    ports:
      - "10000:10000"
    environment:
      - DB_NAME=example
      - DB_USER=nico
      - DB_PASSWORD=abc123.
      - DB_HOST=basededatos
      - DB_PORT=5432
    depends_on:
      - basededatos
  basededatos:
    image: postgres:15
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: nico
      POSTGRES_PASSWORD: abc123.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  default:
    driver: bridge
