services:
  web:
    build:
      context: . # El contexto de construcción es la raíz del proyecto
      dockerfile: Dockerfile # Ruta al Dockerfile dentro de la carpeta to_exercise_project
    command: gunicorn --bind 0.0.0.0:8000 to_exercise_project.wsgi:application
    environment:
      - DATABASE_URL=postgres://nico:abc123.@basededatos:5432/example
    depends_on:
      - basededatos
    ports:
      - "8000:8000"

  basededatos:
    image: postgres:15
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: nico
      POSTGRES_PASSWORD: abc123.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
